# API
services:
  postgrex:
    container_name: postgrex-mono
    build:
      context: apps/api/tools/docker/db
      dockerfile: Dockerfile
      args:
        - CRON_DATABASE_NAME=${DATABASE_NAME}
    restart: unless-stopped
    ports:
      - 9876:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    networks:
      - airgradient-map-staging

  mapapi:
    image: "mapapi-mono:${IMAGE_TAG}"
    container_name: mapapi-mono
    build:
      context: apps/api
      dockerfile: tools/docker/Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - airgradient-map-staging
    env_file:
      - ./apps/api/.env.staging
    depends_on:
      - postgrex
    environment:
      - NODE_ENV=staging

  app:
    image: "website-mono:${IMAGE_TAG}"
    container_name: website-mono
    build:
      context: apps/website
      args:
        - APP_ENV=staging
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - APP_ENV=staging
      - HOST=0.0.0.0
      - PORT=80

  wind-service:
    image: "wind-service-mono:${IMAGE_TAG}"
    container_name: wind-service-mono
    build:
      context: apps/wind-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database
      - DATABASE_HOST=postgrex
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # AWS S3
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - airgradient-map-staging
    depends_on:
      - postgrex

networks:
  airgradient-map-staging:
    driver: bridge

volumes:
  pgdata:
